// Generated by CoffeeScript 1.6.3
var Index, cs;

(require('source-map-support')).install({
  handleUncaughtExceptions: false
});

cs = require('coffee-script');

module.exports = new (Index = (function() {
  var LITERATE;

  function Index() {}

  Index.prototype.polvo = true;

  Index.prototype.type = 'js';

  Index.prototype.name = 'coffee-script';

  Index.prototype.ext = /\.(lit\.)?(coffee)(\.md)?$/m;

  Index.prototype.exts = ['.coffee', '.litcoffee', '.coffee.md'];

  LITERATE = /\.(litcoffee|coffee\.md)$/m;

  Index.prototype.compile = function(filepath, source, done) {
    var bare, compiled, err, js, literate, map, sourceMap;
    bare = 1;
    literate = LITERATE.test(this.filepath);
    sourceMap = 1;
    if (literate) {
      source = source.replace(/^[^\s]+.+$/mg, '');
    }
    try {
      compiled = cs.compile(source, {
        bare: bare,
        sourceMap: sourceMap
      });
      js = compiled.js;
      map = JSON.parse(compiled.v3SourceMap);
      return done(js, JSON.stringify(map, null, 2));
    } catch (_error) {
      err = _error;
      console.error(err.message + ' at ' + this.filepath);
      return done();
    }
  };

  return Index;

})());
